name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Download Android SDK Command-Line Tools
        uses: actions/download-artifact@v3
        with:
          name: android-sdk-cmdline-tools
          path: android-sdk-cmdline-tools

      - name: Extract Android SDK Command-Line Tools
        run: unzip android-sdk-cmdline-tools.zip -d android-sdk-cmdline-tools

      - name: Accept Android SDK Licenses
        run: ./android-sdk-cmdline-tools/bin/sdkmanager --licenses

      - name: Install Android SDK Packages
        run: ./android-sdk-cmdline-tools/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"

      - name: Install dependencies
        run: ./gradlew dependencyCache:clear

      - name: Build app
        run: ./gradlew clean build

      - name: Run unit tests
        run: ./gradlew test

      - name: Check code formatting
        run: ./gradlew ktlintCheck

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-app
          path: app/build/outputs/apk/debug # Replace with your APK path
